name: My_First_Test_Workflow

on : push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Msg
          run: echo "Hello SJ. Good to see you, start learning GitHub Actions"

        - name: List the Files & Directories
          run: ls -ltr