name: My_First_Test_Workflow

on : push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Github Checkout
          uses: actions/checkout@v6

        - name: Multi-line CMD
          run: |
           echo "Hello SJ. Good to see you, start learning GitHub Actions"
           ls -ltra
           cat README.md

        # - name: List the Files & Directories
        #   run: ls -ltr

        # - name: View the file content
        #   run: cat README.md