name: exploring matrix configuration

# The matrix strategy in GitHub Actions allows you to run a single job multiple times using different variable combinations. It is commonly used for cross-platform testing, such as running the same test suite against multiple operating systems and programming language versions simultaneously.

on: push

jobs:
    deploy-on-ubuntu:
        runs-on: ubuntu-latest
        steps:
        - name: Echo Docker Details
          run: docker info

        - name: Run Image
          run: docker run hello-world
    
    deploy-on-windows:
        runs-on: windows-latest
        steps:
        - name: Echo Docker Details
          run: docker info

        - name: Run Image
          run: docker run hello-world