name: exploring matrix strategy additional parameters

# The matrix strategy in GitHub Actions allows you to run a single job multiple times using different variable combinations. It is commonly used for cross-platform testing, such as running the same test suite against multiple operating systems and programming language versions simultaneously.
# In this example we are using mutiple os and images for test.

on: push

jobs:
    deploy:
        strategy:
          fail-fast: false #By default its true, GitHub cancels all in-progress jobs if any matrix job fails
          max-parallel: 2 #The maximum number of jobs that can run simultaneously when using a matrix job strategy.
          matrix:
            os: [ubuntu-latest, ubuntu-22.04, windows-latest]
            images: [hello-world, alpine]
            exclude: #To remove specific configurations defined in the matrix
              - images: alpine
                os: windows-latest
            include: #Use include to expand existing matrix configurations or to add new configurations. The
              - images: amd64/alpine
                os: ubuntu-22.04
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info

        - name: Run Image ${{ matrix.images }}
          run: docker run ${{ matrix.images }}